# Configure relative paths for script execution
rawdataDir: rawdata
procdataDir: procdata
metadataDir: metadata
resultsDir: results
scriptsDir: scripts
logsDir: logs

KALLISTO_version: "0.46.1"

GENCODE_GENOME:
  REF_BUILD: "GRCh38"
  REF_VERSION: "45"


# Configure Data URLs
metadata:
  sampleAnnotation: "https://www.ncbi.nlm.nih.gov/Traces/study/?acc=PRJNA297219&o=acc_s%3Aa"
  treatmentAnnotation: ""

treatmentResponse:
  doseResponse:
    description: "Dose response data"
    url: ""

molecularProfiles:
  rnaseq:
    description: "RNA-Seq"
    url: "https://www.ncbi.nlm.nih.gov/Traces/study/?acc=PRJNA297219&o=acc_s%3Aa"

